name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  Check_scretes:
    name: username and password check
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.EXPO_CLI_USERNAME }}
      - run: echo ${{ secrets.EXPO_CLI_PASSWORD }}
  publish:
    name: Install-and-publish
    needs: [ ci, Check_scretes] 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: mayur1704
          expo-password: Mayur7671@
      - run: yarn install
      - run: expo publish
      
  
  ci:
    name: Daily Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
      - run: yarn install
      - run: expo build:android -t apk
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
             }]
            }
        env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
            if: always() # Pick up events even if the job fails or is canceled
