name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  Check_scretes:
    name: username and password check
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.EXPO_CLI_USERNAME }}
      - run: echo ${{ secrets.EXPO_CLI_PASSWORD }}
